### ISSUE TITLE
Add challenge: top-down accelerometer positioning

### ISSUE THREAD

**Issue by Bone008** [Bone008/Safebusters#16]
A ... thing? ... needs to be positioned at the correct location on the safe.
It can be moved by jabbing the controller in a (horizontal) direction.

The target position is visible on the back side. The player on the back has to press a confirm button when the thing was positioned correctly.

Maybe make it easier by having a status LED that shows when the thing is in (or close to) the correct location.
^--- this could even be one of the outputs of the cactus controller (light up LEDs or start vibrating motor the closer you get)

**Comment by PeterGreth** [comment]
TODO: Implement win and lose logic + UI
