### ISSUE TITLE
Add challenge: synchronous sliders

### ISSUE THREAD

**Issue by Bone008** [Bone008/Safebusters#18]
Sliders on both sides of the safe have to be lowered to 0 at the same time.

The difference may not become too large. Maybe assist with status LEDs to indicate how "dangerous" it is.

**Comment by PeterGreth** [comment]
985bce3

**Comment by PeterGreth** [comment]
985bce3 fixes this. 
Further issues:
-Fix slider positions on back side of safe
-Display the start of the challenge 
-Difference-Feedback as described above
