### ISSUE TITLE
Fix input focus

### ISSUE THREAD

**Issue by Bone008** [Bone008/Safebusters#7]
`hasFocusFront` and `hasFocusBack` in AbstractChallenge do not work yet.

Since we only have 1 player, #6 should probably be done first.

**Comment by PeterGreth** [comment]
I think we dont need them. Each player has the 'focusedSafe' attribute and input will only be redirected to the focused safe.

**Comment by Bone008** [comment]
But we also have "passive" input from the controller (slider positions, acceleration, microphone, ...).
While they are not changed for inactive safes, challenges may want to easily query if they are focused or not on the front or back side.

They shouldn't have to directly search for the players, because the mapping for backwards safes is inverted and challenges shouldn't have to worry about that IMO.
